### ISSUE TITLE
Add the wireframes/UI on the README.md file

### ISSUE THREAD

**Issue by Anushka-shukla** [OpenCodeyard/YouSafe#12]
Keep all the ".png" files in a way that they act as a single entity when visible on the documentation. 
refer: https://github.com/smaranjitghose/girlscript_app/blob/master/MockUp/Mockup01.png

**Comment by lordvins226** [comment]
can you provide the wireframes/ui ?

**Comment by Anushka-shukla** [comment]
@lordvins226 Sure will provide you the wireframes, once they are finalized. They are under review.

**Comment by lordvins226** [comment]
> @lordvins226 Sure will provide you the wireframes, once they are finalized. They are under review.

Great

**Comment by lordvins226** [comment]
Any news for wireframe ?

**Comment by Anushka-shukla** [comment]
The wireframe is still in progress and the ready ones are present on the ReadMe itself. I would request you to refer that and do as done in the attached ref. link - https://github.com/smaranjitghose/girlscript_app/blob/master/MockUp/Mockup01.png
